<?php
/**
 * @var $block \SysPay\Payment\Block\Checkout\PaymentFail
 * @var $escaper \Magento\Framework\Escaper
 */
$failureMessage = $block->getPaymentFailureMessage();
$order = $block->getOrder();
?>
<div class="checkout-success">
    <?php if ($block->getOrderId()) : ?>
        <?php if ($block->getCanViewOrder()) : ?>
            <p><?= $escaper->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $escaper->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php else : ?>
            <p><?= $escaper->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($failureMessage) : ?>
        <p><i>*<?= $escaper->escapeHtml($failureMessage) ?></i></p>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue"
               href="<?= $escaper->escapeUrl($block->getContinueUrl()) ?>"><span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>

